/**
 * Export utility functions for admin data export features
 * Supports CSV export for bookings, patients, and other data
 */

/**
 * Convert array of objects to CSV string
 * @param {Array} data - Array of objects to convert
 * @param {Array} headers - Column headers to include
 * @returns {string} CSV formatted string
 */
export function arrayToCSV(data, headers) {
  if (!data || data.length === 0) return '';

  // Header row
  const headerRow = headers.map((h) => `"${h.label}"`).join(',');

  // Data rows
  const dataRows = data.map((item) =>
    headers
      .map((h) => {
        let value = item[h.key];
        // Handle various data types
        if (value === null || value === undefined) return '';
        if (typeof value === 'object') value = JSON.stringify(value);
        // Escape quotes and wrap in quotes if needed
        return `"${String(value).replace(/"/g, '""')}"`;
      })
      .join(',')
  );

  return [headerRow, ...dataRows].join('\n');
}

/**
 * Download CSV file
 * @param {string} csv - CSV content
 * @param {string} filename - Name of the file to download
 */
export function downloadCSV(csv, filename) {
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  link.setAttribute('href', url);
  link.setAttribute('download', filename);
  link.style.visibility = 'hidden';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}

/**
 * Export bookings to CSV
 * @param {Array} bookings - Array of booking objects
 */
export function exportBookingsToCSV(bookings) {
  const headers = [
    { key: 'patientName', label: 'Patient Name' },
    { key: 'patientEmail', label: 'Email' },
    { key: 'serviceName', label: 'Service' },
    { key: 'date', label: 'Date' },
    { key: 'timeSlot', label: 'Time' },
    { key: 'status', label: 'Status' },
    { key: 'paymentMethod', label: 'Payment' },
    { key: 'price', label: 'Price' },
    { key: 'notes', label: 'Notes' },
  ];

  const csv = arrayToCSV(bookings, headers);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadCSV(csv, `bookings_${timestamp}.csv`);
}

/**
 * Export patients to CSV
 * @param {Array} patients - Array of patient objects
 */
export function exportPatientsToCSV(patients) {
  const headers = [
    { key: 'name', label: 'Full Name' },
    { key: 'email', label: 'Email' },
    { key: 'phone', label: 'Phone' },
    { key: 'status', label: 'Status' },
    { key: 'condition', label: 'Condition' },
    { key: 'totalBookings', label: 'Total Bookings' },
    { key: 'completedSessions', label: 'Completed Sessions' },
    { key: 'joinDate', label: 'Join Date' },
  ];

  const csv = arrayToCSV(patients, headers);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadCSV(csv, `patients_${timestamp}.csv`);
}

/**
 * Export services to CSV
 * @param {Array} services - Array of service objects
 */
export function exportServicesToCSV(services) {
  const headers = [
    { key: 'title', label: 'Service Name' },
    { key: 'category', label: 'Category' },
    { key: 'description', label: 'Description' },
    { key: 'price', label: 'Price' },
    { key: 'duration', label: 'Duration' },
    { key: 'published', label: 'Status' },
  ];

  const csv = arrayToCSV(services, headers);
  const timestamp = new Date().toISOString().slice(0, 10);
  downloadCSV(csv, `services_${timestamp}.csv`);
}

/**
 * Generate admin report with statistics
 * @param {Object} stats - Stats object with totals
 * @returns {string} Formatted report text
 */
export function generateAdminReport(stats) {
  const timestamp = new Date().toLocaleString('en-PK');

  return `
ADMIN REPORT
Generated: ${timestamp}

=== BOOKING STATISTICS ===
Total Bookings: ${stats.totalBookings || 0}
Confirmed: ${stats.confirmed || 0}
Pending: ${stats.pending || 0}
Completed: ${stats.completed || 0}
Cancelled: ${stats.cancelled || 0}

=== PATIENT STATISTICS ===
Total Patients: ${stats.totalPatients || 0}
Active: ${stats.activePatients || 0}
Inactive: ${stats.inactivePatients || 0}

=== FINANCIAL ===
Total Revenue: PKR ${(stats.totalRevenue || 0).toLocaleString('en-PK')}
This Month: PKR ${(stats.revenueThisMonth || 0).toLocaleString('en-PK')}

=== SERVICES ===
Total Services: ${stats.totalServices || 0}
Active Services: ${stats.activeServices || 0}

Generated by Ali's Clinic Admin Panel
`;
}

/**
 * Generate and download admin report
 * @param {Object} stats - Statistics object
 */
export function downloadAdminReport(stats) {
  const report = generateAdminReport(stats);
  const blob = new Blob([report], { type: 'text/plain;charset=utf-8;' });
  const link = document.createElement('a');
  const url = URL.createObjectURL(blob);

  const timestamp = new Date().toISOString().slice(0, 10);
  link.setAttribute('href', url);
  link.setAttribute('download', `admin_report_${timestamp}.txt`);
  link.style.visibility = 'hidden';

  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
}
